version: '3.3'
services:

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Collector
  otel-collector:
    # opentelemetry-collector-contribは、コアのレポジトリに含まれない拡張機能をcollectorに導入するもの
    # https://github.com/open-telemetry/opentelemetry-collector-contrib
    image: otel/opentelemetry-collector-contrib-dev:latest
    command: [--config=/etc/otel-collector-config.yaml, '']
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"     # Prometheus metrics exposed by the collector
      - "8889:8889"     # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"        # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one

  prometheus:
    container_name: mesmer_example_prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    container_name: mesmer_example_grafana
    image: grafana/grafana:latest
    volumes:
      - ./prometheus-datasource.yaml:/etc/grafana/provisioning/datasources/prometheus-datasource.yaml
      - ./dashboards.yaml:/etc/grafana/provisioning/dashboards/prometheus-datasource.yaml
      - ./dashboards:/etc/dashboards
    ports:
      - 3000:3000